# Generated by Django 4.1.3 on 2022-11-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Draft,', 'Draft'), ('Published,', 'Published')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
